import Link from "next/link";

export default function Footer() {
    return (
        <>
            <footer className="bg-light">
                <div className="py-9 md:py-14">
                <div className="container">
                    <p className="font-bold uppercase text-[16px] text-center text-[#686e7d] mb-5">Brands Directory</p>
                    <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
                        <div>
                            <ul className="flex flex-wrap gap-y-3 poppins text-[#686e7d] mb-10">
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Jewellery :</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Necklace</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Earrings</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Couple Rings </Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Pendants</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>crystal</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Bangles</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Nose pin</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Chain</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Earrings</Link></li>                                
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Couple Rings</Link></li>                           
                            </ul>
                            <ul className="flex flex-wrap gap-y-3 poppins text-[#686e7d]">
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Footwear  :</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Sport</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Formal</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Boots</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Casual</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Cowboy Shoes</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Safety Shoes</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Party Wear Shoes</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Branded</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>First Copy</Link></li>                                
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Long Shoes</Link></li>                           
                            </ul>
                        </div>
                        <div>
                            <ul className="flex flex-wrap gap-y-3 poppins text-[#686e7d] mb-10">
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Fashion :</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>T-Shirt</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Short & Jeans</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Jacket </Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Dress & Frock</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Inner Wear</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Hosiery</Link></li>                          
                            </ul>
                            <ul className="flex flex-wrap gap-y-3 poppins text-[#686e7d]">
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Cosmetics  :</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Shampoo</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Body Wash</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Face Wash</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Lipstick</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Perfume</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Body Shop</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Sunscreen</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Skin Lotion</Link></li>
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Scrub</Link></li>                                
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Hair Gel</Link></li>                                
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Hair Colors</Link></li>                                
                                <li className="pe-4 me-4 first:p-0 last:pe-0 first:border-r-0 hover:text-primary cursor-pointer first:cursor-auto first:hover:text-inherit last-of-type:border-r-0 font-normal text-[14px] first:font-semibold border-r-2 leading-3 border-[#686e7d]"><Link href={"/"}>Hair Dye</Link></li>                           
                            </ul>
                        </div>
                    </div>
                </div>
                </div>
            </footer>
        </>
    );
}